( function ( $ ) {
	'use strict';

	var yky = {
		id: 'yky',
		name: 'YKY shorthands',
		description: 'YKY`s shorthands, for testing only.',
		date: '2013-11-17',
		URL: 'http://github.com/Cybernetic1/jquery.ime',
		author: 'YKY',
		license: 'GPLv3',
		version: '1.0',
		patterns: [
["1","one"],
["1st","first"],
["2b","to be"],
["2d","to do"],
["2m","2 or more men"],
["2n","tonight"],
["2nd","second"],
["3rd","third"],
["41t","for the first time"],
[">H","transhumanist"],
["abit","a bit"],
["abt","about"],
["actt","actually"],
["acg","amateur call girl"],
["aft","after"],
["ag","again"],
["agst","against"],
["al","already"],
["algo","algorithm"],
["alm","almost"],
["alo","a lot of"],
["alot","a lot"],
["alr","alright"],
["alw","always"],
["ano","another"],
["ans","answer"],
["arn","around"],
["arnt","arn't"],
["atm","at the moment"],
["atst","at the same time"],
["awl","a while"],
["b","but"],
["b4","before"],
["bc","because"],
["bh","behind"],
["bk","back"],
["bn","been"],
["bng","being"],
["bnth","beneath"],
["bsi","beside"],
["bss","*bzzzzt*"],
["bt","between"],
["btw","by the way"],
["bty","beauty"],
["btyf","beautiful"],
["c","see"],
["c2","come to"],
["cant","can't"],
["cd","could"],
["cdnt","couldn't"],
["cg","call girl"],
["ch","change"],
["chan","channel"],
["chk","check"],
["cmp","compare"],
["comp","computer"],
["cont","continue"],
["cos","cause"],
["ct","chat"],
["cu","can you"],
["d","the"],
["dau","daughter"],
["ddnt","didn't"],
["ddy","daddy"],
["desp","desparate"],
["diff","different"],
["diffc","difference"],
["difft","difficult"],
["dl","download"],
["dn","down"],
["dont","don't"],
["du","do you"],
["e","every"],
["e1","everyone"],
["EA","evolutionary algorithms"],
["ee","e-mail"],
["el","else"],
["em","them"],
["EP","evolutionary programming"],
["epsy","evolutionary psychology"],
["esp","especially"],
["eth","everything"],
["exm","example"],
["exp","experience"],
["f","for"],
["fav","favorite"],
["fex","for example"],
["fn","friend"],
["fr","from"],
["fsy","fantasy"],
["g","girl"],
["g2","go to"],
["GA","genetic algorithms"],
["gb","gangbang"],
["gd","good"],
["GI","general intelligence"],
["GP","genetic programming"],
["gt2","got to"],
["gv","give"],
["h","how"],
["h2","how to"],
["hap","happen"],
["hb","how about"],
["hc","how come"],
["hccg","high class call girl"],
["hed","he'd"],
["hel","he'll"],
["hh","heh"],
["hhh","hehe"],
["hhhh","hehehe"],
["hih","highheel"],
["hm","home"],
["hml","humiliate"],
["hmln","humiliation"],
["hpy","happy"],
["hr","here"],
["hrsf","herself"],
["hsnt","hasn't"],
["hv","have"],
["hvnt","haven't"],
["i","I"],
["i2","into"],
["ic","I see"],
["id","I'd"],
["ifo","in front of"],
["ig","I guess"],
["il","I'll"],
["im","I'm"],
["ind","independent"],
["info","information"],
["inno","innocent"],
["int","interest"],
["intg","intelligence"],
["intr","introduce"],
["irl","in real life"],
["isnt","isn't"],
["itd","it'd"],
["itl","it'll"],
["iv","I've"],
["j","just"],
["je","jealous"],
["k","ok"],
["kb-","KB (knowledgebase)"],
["kd","kind"],
["kk","is that OK?"],
["kn","know"],
["kng","knowledge"],
["ko","kind of"],
["l","like"],
["l2","like to"],
["lang","language"],
["lk","look"],
["ll","will"],
["lo","hello"],
["lt","little"],
["ltm","last time"],
["ltr","later"],
["lv","love"],
["m","more"],
["m2","me too"],
["mb","maybe"],
["md","made"],
["MDL","minimum description length"],
["mem","memory"],
["mf","my friend"],
["mh","much"],
["mk","make"],
["mn","mean"],
["mny","many"],
["mskt","miniskirt"],
["mysf","myself"],
["n","and"],
["n2","need to"],
["nbd","nobody"],
["nc","nice"],
["ne","any"],
["ne1","anyone"],
["nec","necessary"],
["necy","necessarily"],
["nem","anymore"],
["neth","anything"],
["nev","never"],
["neway","anyway"],
["newhr","anywhere"],
["nf","enough"],
["nite","night"],
["nl-","NL (natural language)"],
["nm","nevermind"],
["no1","no one"],
["nt","and then?"],
["nth","nothing"],
["ntm","next time"],
["nty","naughty"],
["nu","and you?"],
["nv","never"],
["nvr","never"],
["nx","next"],
["ny","NY"],
["o","other"],
["obe","obedient"],
["oe","only"],
["ofc","of course"],
["oft","often"],
["ovr","over"],
["ow","otherwise"],
["pattrec","pattern recognition"],
["p","pretty"],
["pb","probably"],
["ph","perhaps"],
["pix","pics"],
["Pc","probabilistic"],
["pll","parallel"],
["poss","possible"],
["ppl","people"],
["prob","problem"],
["prog","program"],
["propr","proprietary"],
["pst","prostitute"],
["pt","point"],
["ptr","particular"],
["pv","private"],
["py","play"],
["q","question"],
["qt","quite"],
["r","are"],
["rem","remember"],
["rep","representation"],
["rl","real"],
["RL","reinforcement learning"],
["rp","roleplay"],
["rpg","roleplaying"],
["rt","right"],
["ru","are you"],
["ruf","rough"],
["ry","really"],
["s1","someone"],
["sc","scene"],
["sci","science"],
["sd","sound"],
["sev","several"],
["sf","self"],
["sg","suggest"],
["shd","should"],
["shdnt","shouldn't"],
["shel","she'll"],
["sht","short"],
["skt","skirt"],
["slp","sleep"],
["sm","same"],
["smv","submissive"],
["sp","special"],
["sq","squeeze"],
["st","still"],
["sth","something"],
["struct","structure"],
["stg","stranger"],
["sty","slutty"],
["sug","suggest"],
["sugn","suggestion"],
["sw","somewhat"],
["sy","sorry"],
["t","that"],
["t2","talk to"],
["t4","therefore"],
["td","that'd"],
["te","their"],
["temp","temporary"],
["tgt","together"],
["th","this"],
["thg","thing"],
["thk","think"],
["tho","though"],
["thr","there"],
["thrd","there'd"],
["thrl","there'll"],
["thro","through"],
["thrr","there're"],
["tht","thought"],
["thy","they"],
["thyd","they'd"],
["thyl","they'll"],
["thyr","they're"],
["thyv","they've"],
["tk","take"],
["tl","that'll"],
["tlk","talk"],
["tm","time"],
["tmr","tomorrow"],
["tn","then"],
["tx","thanks"],
["u","you"],
["u2","you too"],
["uc","you see?"],
["ud","you'd"],
["ul","you'll"],
["un","understand"],
["und","under"],
["undn","underneath"],
["ur","your"],
["ure","you're"],
["urs","yours"],
["ursf","yourself"],
["usa","US"],
["uu","usually"],
["uv","you've"],
["v","very"],
["VC","virtual credit"],
["w","with"],
["w2","want to"],
["wasnt","wasn't"],
["wat","what"],
["watd","what'd"],
["wate","whatever"],
["wd","would"],
["wdnt","wouldn't"],
["wed","we'd"],
["wel","we'll"],
["wer","we're"],
["werent","weren't"],
["wev","we've"],
["wh","which"],
["whl","whole"],
["whod","who'd"],
["whr","where"],
["wi","within"],
["wk","work"],
["wko","what kind of"],
["wl","while"],
["wn","when"],
["wo","without"],
["wont","won't"],
["wr","wear"],
["wrk","work"],
["wsp","whisper"],
["wt","want"],
["wubson","would you be shy or nervous"],
["ww","woman"],
["x","cause"],
["y","why"],
["ye","yeah"],
["yn","why not?"],
["yng","young"],
["yngr","younger"],
["ytd","yesterday"],
['cyb1', '半機器人一號']]
	};

	$.ime.register( yky );
}( jQuery ) );
